baseURL = "https://your-domain.com/"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "硅基突触"
theme = "hugo-blog-awesome"

[languages.zh]
  title = "硅基突触"
  languageName = "中文"
  weight = 1

[languages.en]
  title = "Silicon Synapse"
  languageName = "English" 
  weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"