baseURL = "http://8.138.251.169/"
languageCode = "zh-cn"
title = "硅基突触"
description = "在碳基生命与硅基智能的交汇处，我们记录AI技术的每一次突触连接。这里不仅是代码与算法的集合，更是对人类认知边界的前沿探索，思考机器如何重塑我们的思维方式与世界认知。"
theme = "hugo-blog-awesome"

# ✅ 替换 paginate
[pagination]
  pagerSize = 10

# 基础设置
buildDrafts = false
buildFuture = false
buildExpired = false

# ✅ 主题参数
[params]
  description = "在碳基生命与硅基智能的交汇处，我们记录AI技术的每一次突触连接。这里不仅是代码与算法的集合，更是对人类认知边界的前沿探索，思考机器如何重塑我们的思维方式与世界认知。"
  dateFormat = "2006-01-02"
  colorScheme = "auto"
  enableSearch = true
  enableTags = true
  enableCategories = true
  toc = true
  showReadingTime = true

# ✅ 正确的 author 格式
[params.author]
  avatar = "images/avatar.png"
  intro = "硅基突触"
  name = "Yuanhua Chang"
  description = "在碳基生命与硅基智能的交汇处，我们记录AI技术的每一次突触连接。这里不仅是代码与算法的集合，更是对人类认知边界的前沿探索，思考机器如何重塑我们的思维方式与世界认知。"

# ✅ 页脚配置
[params.footer]
  since = 2024
  poweredBy = true
  copyright = "© 2025 Yuanhua"

# ✅ 导航菜单
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 5
